changelog:
  - title: '💥 Breaking Changes'
    labels:
      - 💥 breaking
  - title: '✨ Enhancements'
    labels:
      - ✨ enhancement
  - title: '🐛 Bug Fixes'
    labels:
      - 🐛 bug
  - title: '🏗 Maintenance'
    labels:
      - 🧹 maintenance
      - 📝 documentation
  - title: '⬆️⬇️ Dependency Updates'
    labels:
      - ⬆️⬇️ dependencies
