name: Build Executables
on: push
jobs:
  lint:
    name: Build Executables
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Install gon via HomeBrew for code signing and app notarization
        run: |
          brew tap mitchellh/gon
          brew install mitchellh/gon/gon
      - run: ./scripts/build.sh
        env:
          APPLE_DEV_CERT: ${{secrets.APPLE_DEV_CERT}}
          APPLE_ID_USERNAME: ${{secrets.APPLE_ID_USERNAME}}
          APPLE_ID_KEY: ${{secrets.APPLE_ID_KEY}}
      - uses: actions/upload-artifact@v3
        with:
          name: macos executable
          path: percy-macos
      - uses: actions/upload-artifact@v3
        with:
          name: linux executable
          path: percy-linux
      - uses: actions/upload-artifact@v3
        with:
          name: win executable
          path: percy-win.exe
