name: Lint
on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - uses: actions/cache@v2
        with:
          path: |
            node_modules
            packages/*/node_modules
            packages/core/.local-chromium
          key: >
            ${{ runner.os }}/node-14/
            ${{ hashFiles('.github/.cache-key') }}/
            ${{ hashFiles('**/yarn.lock') }}
          restore-keys: >
            ${{ runner.os }}/node-14/
            ${{ hashFiles('.github/.cache-key') }}/
      - run: yarn
        env:
          PERCY_POSTINSTALL_BROWSER: true
      - run: yarn lint
