name: Lint
on: push
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - uses: actions/cache@v2
        with:
          path: |
            node_modules
            packages/*/node_modules
            packages/core/.local-chromium
          key: v1/${{ runner.os }}/node-14/${{ hashFiles('**/yarn.lock') }}
          restore-keys: v1/${{ runner.os }}/node-14/
      - run: yarn
        env:
          PERCY_POSTINSTALL_BROWSER: true
      - run: yarn lint
